### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by LucasZdv** [captive/oc-calendar-plugin#3]
Hi, some example?

**Comment by LukeTowers** [comment]
https://github.com/captive/oc-calendar-plugin/blob/master/docs/example.config_calendar.yaml

**Comment by LucasZdv** [comment]
"A widget with class name 'calendar' has not been bound to the controller" on line 598 of /srv/users/development/apps/dev-visitarsanluis/public/modules/backend/classes/Controller.php


https://nimb.ws/hOXeSf

**Comment by LukeTowers** [comment]
@LucasZdv what's your controller file look like? What version of PHP and OctoberCMS are you using?

**Comment by LucasZdv** [comment]
```
<?php namespace Awebsome\Booking\Controllers;

use BackendMenu;
use Backend\Classes\Controller;

/**
 * Bookings Back-end Controller
 */
class Bookings extends Controller
{
    public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
        'Captive.Calendar.Behaviors.CalendarController'
    ];

    public $formConfig = 'config_form.yaml';
    public $listConfig = 'config_list.yaml';
    public $calendarConfig = 'config_calendar.yaml';

    public $requiredPermissions = ['awebsome.booking.advertiser.bookings'];
    /**
     * @var string HTML body tag class
     */
    public $bodyClass = 'compact-container';

    public function __construct()
    {
        parent::__construct();

        BackendMenu::setContext('Awebsome.Booking', 'booking', 'bookings');
    }
}

```

PHP 7.3
Build 455

**Comment by LukeTowers** [comment]
@LucasZdv try switching to the latest dev branch of October. This plugin was made with the latest dev branch and not tested on anything else.

**Comment by LukeTowers** [comment]
@LucasZdv Also, what are you doing that's triggering the error?

**Comment by fansaien** [comment]
@LucasZdv  Hello, Did you try this in your index.html
```php
<?= $this->calendarRender() ?>
```

**Comment by LucasZdv** [comment]
Upgrade to version 456. but the error is the same, this happens when loading the page. I'm not sure I implemented the widget correctly, so I was requesting an example not only from the configuration yaml.

My index.htm

```
<? $this->makeCalendar() ?>
<?= $this->calendarRender() ?>
```

If I do not put this

`<? $this->makeCalendar() ?>`

It shows me this error:
Calendar behavior has not been initialized, check that you have called makeCalendar () in your controller.

**Comment by LukeTowers** [comment]
By default the controller action included by the behaviour is `calendar()` not `index()`. In order to return the calendar from `index()` you need to make sure that you have the following in your controller:
```php
public function index()
{
    return $this->asExtension('CalendarController')->calendar();
}
```

**Comment by LucasZdv** [comment]
Well, it works with calendar() thanks!
