### ISSUE TITLE
Full Calendar 5.7

### ISSUE THREAD

**Issue by xyz1123581321** [captive/oc-calendar-plugin#6]
Can we get an update for FullCalendar 5.7 version?

**Comment by fansaien** [comment]
The FullCalendar supports rrule now. Before that, I did the rrule on my side. So, I need to do more tests. But, I will update it.

**Comment by fansaien** [comment]
In the new version, only the Premium plan can support the Timeline View and Vertical Resource View. I can not update it for now.

**Comment by xyz1123581321** [comment]
will there be an update for FullCalendar 6^?

**Comment by LukeTowers** [comment]
@xyz1123581321 I'm planning on adding FullCalendar 6 to Winter CMS: https://github.com/wintercms/winter/pull/970

**Comment by xyz1123581321** [comment]
@LukeTowers that will be really nice built-in feature!

**Comment by xyz1123581321** [comment]
@LukeTowers do you maybe know why the calendar isnt refreshing the records on filter update?

**Comment by fansaien** [comment]
> will there be an update for FullCalendar 6^?

I will update it to FullCalendar 6.1

**Comment by xyz1123581321** [comment]
Oh that would also be nice! How long will it take? Do you need any help?
Current version, Im not sure but I think $(document).on('ajaxComplete', this.proxy(this.onFilterUpdate)); is not triggered on Filter "Apply" button, and it does not filter right away, you either need to refresh or update calendar widget.

**Comment by xyz1123581321** [comment]
Oh that would also be nice! How long will it take? Do you need any help?
Current version, Im not sure but I think $(document).on('ajaxComplete', this.proxy(this.onFilterUpdate)); is not triggered on Filter "Apply" button, and it does not filter right away, you either need to refresh or update calendar widget.

**Comment by LukeTowers** [comment]
@xyz1123581321 if you're interested in contributing I'd welcome the help on the Winter PR 😉

**Comment by fansaien** [comment]
@xyz1123581321  I plan to do that may be next week or after next week.
For the onFilterUpdate, please review this: https://github.com/captive/oc-calendar-plugin/commit/94b815a3cf8b0acca1456601090875beaa191c67
If the framework.js changed, you need to update the parameters.

**Comment by xyz1123581321** [comment]
@LukeTowers I would love to! Let me see to manage my time! Thank you!
@fansaien I tried with ajax:request-complete, still it doesnt update the events. Will check other things.

`
this.migratejQueryEvent(document, 'ajax:request-complete', 'ajaxComplete', ['context', 'data', 'responseCode', 'xhr']);
`
```
key: "notifyApplicationRequestComplete",
    value: function notifyApplicationRequestComplete(data, responseCode, xhr) {
      return (0,_util__WEBPACK_IMPORTED_MODULE_6__.dispatch)('ajax:request-complete', {
        target: this.triggerEl,
        detail: {
          context: this.context,
          data: data,
          responseCode: responseCode,
          xhr: xhr
        }
      });
    }
```

**Comment by xyz1123581321** [comment]
@fansaien did you test it if it is updating when filtering? I tried different things, still not working, currently I'm redrawing the calendar partial

**Comment by fansaien** [comment]
Yes, it is working on my project
